name: flutter_bloc_architecture_template
description: "A Template for Flutter app using Bloc Architecture"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  go_router: ^16.2.0
  logging: ^1.3.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  url_strategy: ^0.3.0
  url_launcher: ^6.3.2

  crypto: ^3.0.6

  app_core:
    path: ./packages/app_core
  app_auth:
    path: ./packages/app_auth
  sample_package_structure:
    path: ./packages/sample_package_structure

  intl: ^0.19.0
  uuid: ^4.5.1

  font_awesome_flutter: ^10.9.1
  get_it: ^8.2.0

  flutter_localizations:
    sdk: flutter

  html: ^0.15.6
  http: ^1.5.0
  google_fonts: ^6.3.0
  dynamic_color: ^1.8.1
  material_color_utilities: ^0.11.1
  shared_preferences: ^2.5.3
  file_picker: ^10.3.2
  file_saver: ^0.3.1
  path_provider: ^2.1.5
  flutter_native_splash: ^2.4.6
  flutter_staggered_grid_view: ^0.7.0
  flutter_markdown: ^0.7.7+1
  formz: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
flutter:
  default-flavor: dev
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/files/
